#!/usr/bin/env python3
"""
Script to update the UK tenancy statutes whitelist in app/validate_legal_refs.py

This script compiles a comprehensive list of UK housing/tenancy legislation
based on authoritative sources and known acts.
"""

# Comprehensive list of UK Housing/Tenancy Acts
# Sources:
# - legislation.gov.uk
# - UK government housing guidance
# - Legal research databases

UK_TENANCY_STATUTES = {
    # Housing Acts (major legislation)
    "Housing Act 1985",
    "Housing Act 1988",
    "Housing Act 1996",
    "Housing Act 2004",
    "Housing Act",
    
    # Landlord and Tenant Acts
    "Landlord and Tenant Act 1927",
    "Landlord and Tenant Act 1954",
    "Landlord and Tenant Act 1985",
    "Landlord and Tenant Act 1987",
    "Landlord and Tenant Act",
    
    # Protection and Eviction
    "Protection from Eviction Act 1977",
    "Protection from Eviction Act",
    
    # Tenant Fees and Rights
    "Tenant Fees Act 2019",
    "Tenant Fees Act",
    "Homes (Fitness for Human Habitation) Act 2018",
    "Homes Act 2018",
    "Homes (Fitness for Human Habitation) Act",
    
    # Consumer Protection (relevant for tenancy)
    "Consumer Rights Act 2015",
    "Consumer Rights Act",
    "CRA 2015",
    
    # Unfair Terms
    "Unfair Contract Terms Act 1977",
    "UCTA 1977",
    
    # Rent Acts (historical but still referenced)
    "Rent Act 1977",
    "Rent Act",
    
    # Leasehold Reform
    "Leasehold Reform Act 1967",
    "Leasehold Reform, Housing and Urban Development Act 1993",
    "Leasehold Reform Act",
    
    # Common Law
    "UK common law",
    "English common law",
    "common law",
}

# Additional statutes that may be referenced in tenancy contexts
ADDITIONAL_RELEVANT_STATUTES = {
    "Equality Act 2010",  # Discrimination in housing
    "Data Protection Act 2018",  # Tenant data
    "Gas Safety (Installation and Use) Regulations 1998",
    "Electrical Safety Standards in the Private Rented Sector (England) Regulations 2020",
    "Smoke and Carbon Monoxide Alarm (England) Regulations 2015",
    "Energy Efficiency (Private Rented Property) (England and Wales) Regulations 2015",
}

def generate_statutes_list():
    """Generate formatted list for VALID_UK_STATUTES set."""
    all_statutes = sorted(UK_TENANCY_STATUTES | ADDITIONAL_RELEVANT_STATUTES)
    
    print("# Comprehensive UK Tenancy/Housing Statutes")
    print("# Generated by scripts/update_uk_tenancy_statutes.py")
    print("# Sources: legislation.gov.uk, UK government guidance")
    print("")
    print("VALID_UK_STATUTES = {")
    for statute in all_statutes:
        print(f'    "{statute}",')
    print("}")
    print("")
    print(f"# Total: {len(all_statutes)} statutes")

if __name__ == "__main__":
    generate_statutes_list()
